version: '3'

services:
  db-confin:
    image: postgres:alpine
    ports:
      - "6000:5432"
    container_name: "db-confin"
    restart: always
    volumes:
      - ./db-confin:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: db-confin
      POSTGRES_PASSWORD: confin
      PGDATA: /var/lib/postgresql/data/some_name/
volumes:
  db-confin: